

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 22-156B-9052-13			    |
; |				 Licensed User				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	9EE47146483D863A2AA37BEA87742E3A

; File Name   :	C:\Users\Furious George\Desktop\iClicker\iClicker flash	unfuckedwith.hex
; Format      :	Intel Hex Object Format

; Processor	  : AVR	     [ATmega8_L]
; Target assembler: AVR	Assembler


; Segment type:	Pure code
.CSEG ;	ROM
.org 0


; Store	Program	Memory Ready
; Attributes: noreturn

; public SPM_RDY
SPM_RDY:
rjmp	__RESET		; INT1_
; End of function SPM_RDY ; TIMER2_COMP
			; TIMER2_OVF
			; TIMER1_CAPT
			; TIMER1_COMPA
			; TIMER1_COMPB
			; TIMER1_OVF
			; SPI_STC
			; USART_RXC
			; USART_UDRE
			; USART_TXC
			; EE_RDY
			; ANA_COMP
			; TWI_
.org 1
rjmp	INT0_		; External Interrupt Request 0
.org 2
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 3
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 4
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 5
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 6
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 7
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 8
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 9
rjmp	TIMER0_OVF	; Timer/Counter0 Overflow
.org 0xA
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0xB
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0xC
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0xD
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0xE
rjmp	ADC_		; ADC Conversion Complete
.org 0xF
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0x10
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0x11
rjmp	SPM_RDY		; Store	Program	Memory Ready
.org 0x12
rjmp	SPM_RDY		; Store	Program	Memory Ready
.dw	 0


; External Pin,	Power-on Reset,	Brown-out
; Attributes: noreturn

; public __RESET
__RESET:

; FUNCTION CHUNK AT 0046 SIZE 00000174 BYTES

cli
clr	r30
out	EECR, r30
ldi	r31, 1
out	GICR, r31
out	GICR, r30
out	MCUCR, r30
ldi	r31, 0x18
out	WDTCR, r31
out	WDTCR, r30
ldi	r24, 0xD
ldi	r26, 2
clr	r27

loc_21:
st	X+, r30
dec	r24
brne	loc_21
ldi	r24, 0
ldi	r25, 4
ldi	r26, 0x60 ; '`'

loc_27:
st	X+, r30
sbiw	r24, 1
brne	loc_27
ldi	r30, 0x26 ; '&'
ldi	r31, 0

loc_2C:
lpm	r24, Z+
lpm	r25, Z+
sbiw	r24, 0
breq	loc_3C
lpm	r26, Z+
lpm	r27, Z+
lpm	r0, Z+
lpm	r1, Z+
movw	r22, r30
movw	r30, r0

loc_36:
lpm	r0, Z+
st	X+, r0
sbiw	r24, 1
brne	loc_36
movw	r30, r22
rjmp	loc_2C

loc_3C:
ldi	r30, 0x5F ; '_'
out	SPL, r30
ldi	r30, 4
out	SPH, r30
ldi	r28, 0x60 ; '`'
ldi	r29, 1
rjmp	loc_46
; End of function __RESET




sub_43:
lds	r30, unk_200172
ret
; End of function sub_43

; START	OF FUNCTION CHUNK FOR __RESET

loc_46:
rcall	sub_1BB

loc_47:
ser	r30
sts	unk_200162, r30
sbrs	r4, 4
rjmp	loc_88
cli
ldi	r30, -0x11 ; 'Ô'
and	r4, r30
sei
lds	r30, unk_20016E
lds	r31, unk_20016F
sbiw	r30, 1
sts	unk_20016E, r30
sts	unk_20016F, r31
sbiw	r30, 0
brne	loc_5C
rcall	sub_70E

loc_5C:
lds	r30, unk_200170
lds	r31, unk_200171
sbiw	r30, 1
sts	unk_200170, r30
sts	unk_200171, r31
sbiw	r30, 0
brne	loc_68
rcall	sub_715

loc_68:
rcall	sub_71C
breq	loc_73
lds	r30, unk_20016C
lds	r31, unk_20016D
sbiw	r30, 1
sts	unk_20016C, r30
sts	unk_20016D, r31

loc_73:
rcall	sub_722
breq	loc_7A
lds	r30, unk_200169
subi	r30, 1
sts	unk_200169, r30

loc_7A:
rcall	sub_28A
sts	unk_200162, r30
lds	r26, unk_200162
cpi	r26, 0x11
brne	loc_86
rcall	sub_334
rcall	sub_726
ldi	r30, 0
sts	unk_200163, r30

loc_86:
rcall	sub_244
rcall	sub_393

loc_88:
lds	r26, unk_200162
cpi	r26, 1
brne	loc_8D
rcall	sub_72A

loc_8D:
lds	r26, unk_200162
cpi	r26, 0x12
brne	loc_95
rcall	sub_216
st	-Y, r31
st	-Y, r30
rcall	sub_1F0

loc_95:
lds	r30, unk_200172
cpi	r30, 0
breq	loc_9B
rcall	sub_72F
brne	loc_9C

loc_9B:
rjmp	loc_9D

loc_9C:
rcall	sub_72A

loc_9D:
lds	r26, unk_200162
cpi	r26, 0x13
brne	loc_B4
ldi	r30, 1
sts	unk_200172, r30
ldi	r30, 3
ldi	r31, 0
rcall	sub_733
ldi	r30, -0x7F ; 'Å'
ldi	r31, -0x72 ; 'é'
rcall	sub_736
ldi	r30, 0xF
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x60 ; '†'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rcall	sub_739
ldi	r30, 8
sts	unk_200163, r30

loc_B4:
lds	r30, unk_200163
cpi	r30, 0
brne	loc_D8
rcall	sub_72F
breq	loc_D7
rcall	sub_740
brne	loc_BE
ldi	r16, 0x21 ; '!'
rjmp	loc_CB

loc_BE:
cpi	r30, 4
brne	loc_C2
ldi	r16, 0x22 ; '"'
rjmp	loc_CB

loc_C2:
cpi	r30, 8
brne	loc_C6
ldi	r16, 0x23 ; '#'
rjmp	loc_CB

loc_C6:
cpi	r30, 0x20 ; ' '
brne	loc_CA
ldi	r16, 0x24 ; '$'
rjmp	loc_CB

loc_CA:
ser	r16

loc_CB:
cpi	r16, -1
breq	loc_D7
rcall	sub_744
sts	unk_200160, r30
sts	unk_200161, r31
rcall	sub_747
rcall	sub_74A
ldi	r30, 1
sts	unk_200163, r30

loc_D7:
rjmp	loc_1A9

loc_D8:
cpi	r30, 1
brne	loc_100
rcall	sub_72F
breq	loc_FF
rcall	sub_740
brne	loc_E0
ldi	r16, 0x41 ; 'A'
rjmp	loc_ED

loc_E0:
cpi	r30, 4
brne	loc_E4
ldi	r16, 0x42 ; 'B'
rjmp	loc_ED

loc_E4:
cpi	r30, 8
brne	loc_E8
ldi	r16, 0x43 ; 'C'
rjmp	loc_ED

loc_E8:
cpi	r30, 0x20 ; ' '
brne	loc_EC
ldi	r16, 0x44 ; 'D'
rjmp	loc_ED

loc_EC:
ser	r16

loc_ED:
cpi	r16, -1
breq	loc_FF
lds	r30, unk_200160
lds	r31, unk_200161
mov	r31, r30
ldi	r30, 0
movw	r26, r30
rcall	sub_744
or	r30, r26
or	r31, r27
rcall	sub_74D
ldi	r30, 2
sts	unk_200165, r30
rcall	sub_754
rcall	sub_758

loc_FF:
rjmp	loc_1A9

loc_100:
cpi	r30, 2
brne	loc_10B
ldi	r30, 0x41 ; 'A'
ldi	r31, 0x21 ; '!'
rcall	sub_74D
rcall	sub_330
ldi	r30, 1
sts	unk_200167, r30
ldi	r30, 0xA
rjmp	loc_1A7

loc_10B:
cpi	r30, 3
brne	loc_111
rcall	sub_75C
rcall	sub_602
rcall	sub_764
rjmp	loc_1A7

loc_111:
cpi	r30, 4
brne	loc_117
rcall	sub_75C
rcall	sub_5A2
rcall	sub_764
rjmp	loc_1A7

loc_117:
cpi	r30, 5
brne	loc_143
rcall	sub_71C
brne	loc_136
lds	r26, unk_200166
cpi	r26, 3
brcc	loc_128
lds	r30, unk_200166
subi	r30, -1
sts	unk_200166, r30
ldi	r30, 6
sts	unk_200163, r30
rjmp	loc_134

loc_128:
rcall	sub_76D
rcall	sub_318
rcall	sub_770
lds	r26, unk_200165
cpi	r26, 2
brne	loc_131
ldi	r30, 0
rjmp	loc_132

loc_131:
ldi	r30, 0xA

loc_132:
sts	unk_200168, r30

loc_134:
rcall	sub_58A
rjmp	loc_142

loc_136:
rcall	sub_774
brne	loc_142
rcall	sub_739
clr	r5
rcall	sub_777
rcall	sub_77A
rcall	sub_770
ldi	r30, 0xA
sts	unk_200168, r30
rcall	sub_58A
rcall	sub_330

loc_142:
rjmp	loc_1A9

loc_143:
cpi	r30, 6
brne	loc_15D
lds	r26, unk_200166
cpi	r26, 2
brne	loc_153
lds	r26, unk_20016E
lds	r27, unk_20016F
cpi	r26, 1
ldi	r30, 0
cpc	r27, r30
brne	loc_152
rcall	sub_77D

loc_152:
rjmp	loc_15C

loc_153:
lds	r26, unk_200170
lds	r27, unk_200171
cpi	r26, 1
ldi	r30, 0
cpc	r27, r30
brne	loc_15C
rcall	sub_77D

loc_15C:
rjmp	loc_1A9

loc_15D:
cpi	r30, 7
brne	loc_168
lds	r30, unk_200186
cpi	r30, 0
brne	loc_167
lds	r30, unk_200168
sts	unk_200163, r30

loc_167:
rjmp	loc_1A9

loc_168:
cpi	r30, 0xA
brne	loc_191
rcall	sub_72F
breq	loc_190
rcall	sub_740
brne	loc_170
ldi	r30, 1
rjmp	loc_181

loc_170:
cpi	r30, 4
brne	loc_174
ldi	r30, 5
rjmp	loc_181

loc_174:
cpi	r30, 8
brne	loc_178
ldi	r30, 0xD
rjmp	loc_181

loc_178:
cpi	r30, 0x20 ; ' '
brne	loc_17C
ldi	r30, 0xE
rjmp	loc_181

loc_17C:
cpi	r30, 0x10
brne	loc_180
ldi	r30, 0xA
rjmp	loc_181

loc_180:
ser	r30

loc_181:
sts	unk_200165, r30
lds	r26, unk_200165
cpi	r26, -1
breq	loc_190
lds	r30, unk_200167
cpi	r30, 0
breq	loc_18E
rcall	sub_754
rcall	sub_726
rjmp	loc_18F

loc_18E:
rcall	sub_77D

loc_18F:
rcall	sub_758

loc_190:
rjmp	loc_1A9

loc_191:
cpi	r30, 8
brne	loc_19C
rcall	sub_304
lds	r30, unk_200164
ori	r30, 5
st	-Y, r30
rcall	sub_5A2
clr	r5
ldi	r30, 9
rjmp	loc_1A7

loc_19C:
cpi	r30, 9
brne	loc_1A4
rcall	sub_774
brne	loc_1A3
clr	r5
rcall	sub_747
rcall	sub_77A

loc_1A3:
rjmp	loc_1A9

loc_1A4:
rcall	sub_76D
rcall	sub_74A
ldi	r30, 0

loc_1A7:
sts	unk_200163, r30

loc_1A9:
rcall	sub_722
brne	loc_1B9
lds	r30, unk_20016A
lds	r31, unk_20016B
sbiw	r30, 1
sts	unk_20016A, r30
sts	unk_20016B, r31
sbiw	r30, 0
brne	loc_1B8
rcall	sub_72A
.dw 0xC001 ;  ¿

loc_1B8:
rcall	sub_781

loc_1B9:
rjmp	loc_47
; END OF FUNCTION CHUNK	FOR __RESET
.dw 0xCFFF ;  œ



sub_1BB:
cli
ldi	r30, 0x2E ; '.'
out	DDRB, r30
ldi	r30, 2
out	PORTB, r30
ldi	r30, -8	; '¯'
out	DDRD, r30
out	PORTD, r30
ldi	r30, 0
out	DDRC, r30		;set all portc pins to read
ldi	r30, 0x3F ; '?'
out	PORTC, r30		;
rcall	set_ADC_settings_and_portB_output_sub_231
rcall	sub_2F6
rcall	sub_284
rcall	sub_21A
rcall	sub_446
rcall	sub_1F9
clr	r4
ldi	r30, 0
sts	unk_20016C, r30
sts	unk_20016D, r30
rcall	sub_781
ldi	r30, 0x2C ; ','
ldi	r31, 1
sts	unk_20016A, r30
sts	unk_20016B, r31
rcall	sub_70E
rcall	sub_715
rcall	sub_726
ldi	r30, 0
sts	unk_200164, r30
rcall	sub_68E
ldi	r30, 2
sts	unk_200163, r30
ldi	r30, 3
out	MCUCR, r30
ldi	r30, 0x40 ; '@'
out	GIFR, r30
out	GICR, r30
sei
ret
; End of function sub_1BB



; External Interrupt Request 0

; public INT0_
INT0_:
st	-Y, r30
ldi	r30, 1
mov	r5, r30
ld	r30, Y+
reti
; End of function INT0_



; Attributes: noreturn

sub_1F0:
cli
rcall	sub_32B
ld	r30, Y
ldd	r31, Y+1
sbiw	r30, 0
breq	loc_1F7
rcall	sub_733

loc_1F7:
cbi	PORTB, PORTB1

loc_1F8:
rjmp	loc_1F8
; End of function sub_1F0




sub_1F9:
ldi	r30, 1
out	TIFR, r30
out	TIMSK, r30
ldi	r30, 4
out	TCCR0, r30
rcall	sub_785
ret
; End of function sub_1F9



; Timer/Counter0 Overflow

; public TIMER0_OVF
TIMER0_OVF:
st	-Y, r30
in	r30, SREG
st	-Y, r30
rcall	sub_785
ldi	r30, 0x10
or	r4, r30
ld	r30, Y+
out	SREG, r30
ld	r30, Y+
reti
; End of function TIMER0_OVF




sub_20A:
ldi	r26, 0
ldi	r27, 0
rcall	eeprom_read_sub_869
ret
; End of function sub_20A




sub_20E:
ldi	r26, 1
ldi	r27, 0
rcall	eeprom_read_sub_869
ret
; End of function sub_20E




sub_212:
ldi	r26, 2
ldi	r27, 0
rcall	eeprom_read_sub_869
ret
; End of function sub_212




sub_216:
ldi	r26, 0x40 ; '@'
ldi	r27, 0
rcall	sub_865
ret
; End of function sub_216




sub_21A:
st	-Y, r16
ldi	r30, 0x59 ; 'Y'
out	SPCR, r30
in	r16, SPSR
in	r16, SPDR
ldi	r16, 0
sbi	PORTB, PORTB2
ld	r16, Y+
ret
; End of function sub_21A




sub_223:

; FUNCTION CHUNK AT 0580 SIZE 00000002 BYTES

st	-Y, r16
cli
ldd	r30, Y+1
out	SPDR, r30

loc_227:
in	r30, SPSR
andi	r30, -0x80
cpi	r30, -0x80 ; 'Ä'
brne	loc_227
in	r16, SPSR
in	r16, SPDR
sei
mov	r30, r16
ld	r16, Y
rjmp	loc_580
; End of function sub_223




set_ADC_settings_and_portB_output_sub_231:
ldi	r30, 0x47 ; 'G'	;
out	ADMUX, r30		;set ADC settings(threshholds) with value 0x47
ldi	r30, 0xE
out	ADCSRA,	r30		;set ADC status & control register with value 0xE
sbi	DDRB, DDB0		;set PORTB pin0 to WRITE
cbi	PORTB, PORTB0	;
ser	r30				;r30=1 (set register)
ldi	r31, 3			
sts	unk_200173, r30
sts	unk_200174, r31
ldi	r30, 0x44 ; 'D'
ldi	r31, 0x16
sts	unk_200175, r30
sts	unk_200176, r31
ret
; End of function set_ADC_settings_and_portB_output_sub_231




sub_244:
lds	r30, unk_200175
lds	r31, unk_200176
adiw	r30, 1
sts	unk_200175, r30
sts	unk_200176, r31
lds	r26, unk_200175
lds	r27, unk_200176
cpi	r26, 0x6F ; 'o'
ldi	r30, 0x17
cpc	r27, r30
brne	loc_258
sbi	PORTB, PORTB0
sbi	ADCSRA,	ADEN
rjmp	locret_268

loc_258:
lds	r26, unk_200175
lds	r27, unk_200176
cpi	r26, 0x70 ; 'p'
ldi	r30, 0x17
cpc	r27, r30
brcs	locret_268
ldi	r30, 0
sts	unk_200175, r30
sts	unk_200176, r30
in	r30, ADCSRA
ori	r30, -0x40
out	ADCSRA,	r30

locret_268:
ret
; End of function sub_244



; ADC Conversion Complete

; public ADC_
ADC_:
st	-Y, r30
st	-Y, r31
in	r30, SREG
st	-Y, r30
in	r30, ADCL
in	r31, ADCH
sts	unk_200173, r30
sts	unk_200174, r31
in	r30, ADCSRA
andi	r30, 0x3F
out	ADCSRA,	r30
cbi	PORTB, PORTB0
ld	r30, Y+
out	SREG, r30
ld	r31, Y+
ld	r30, Y+
reti
; End of function ADC_




sub_27C:
lds	r26, unk_200173
lds	r27, unk_200174
ldi	r30, 0x1C
ldi	r31, 2
rcall	sub_85F
ret
; End of function sub_27C




sub_284:
rcall	sub_788
sts	unk_200177, r30
rcall	sub_78C
rcall	sub_790
ret
; End of function sub_284




sub_28A:
rcall	sub_881
ser	r17
lds	r30, unk_200178
subi	r30, -1
sts	unk_200178, r30
in	r30, PINC
andi	r30, 0x3F
ldi	r26, 0x3F ; '?'
eor	r30, r26
mov	r16, r30
lds	r30, unk_20017A
cpi	r30, 0
breq	loc_2C1
cpi	r16, 1
brne	loc_2A1
rcall	sub_797
brcc	loc_2A0
rcall	sub_7A1
rjmp	loc_2F4

loc_2A0:
rjmp	loc_2C1

loc_2A1:
cpi	r16, 9
brne	loc_2A8
rcall	sub_7A8
brne	loc_2A7
ldi	r30, 0x12
rjmp	loc_2F4

loc_2A7:
rjmp	loc_2C1

loc_2A8:
cpi	r16, 0x21 ; '!'
brne	loc_2AF
rcall	sub_797
brcc	loc_2AE
rcall	sub_7A1
rjmp	loc_2F4

loc_2AE:
rjmp	loc_2C1

loc_2AF:
cpi	r16, 0x23 ; '#'
brne	loc_2B7
rcall	sub_7A8
brne	loc_2B6
rcall	sub_790
ldi	r30, 0x13
rjmp	loc_2F4

loc_2B6:
rjmp	loc_2C1

loc_2B7:
ldi	r30, 0
sts	unk_20017A, r30
rcall	sub_7A8
brne	loc_2BE
ldi	r30, 1
rjmp	loc_2F4

loc_2BE:
ldi	r30, 0
sts	unk_200179, r30

loc_2C1:
rcall	sub_7AC
brne	loc_2C9
rcall	sub_78C
cpi	r16, 0
brne	loc_2C9
rcall	sub_788
sts	unk_200179, r30

loc_2C9:
rcall	sub_7AC
breq	loc_2CF
lds	r26, unk_200178
cpi	r26, 3
brcc	loc_2D0

loc_2CF:
rjmp	loc_2F3

loc_2D0:
rcall	sub_78C
sts	unk_200177, r16
lds	r30, unk_20017B
cpi	r30, 0
brne	loc_2F3
cpi	r16, 1
brne	loc_2DD
ldi	r30, 1
sts	unk_20017A, r30
rjmp	loc_2F0

loc_2DD:
cpi	r16, 2
brne	loc_2E1
ldi	r17, 2
rjmp	loc_2F0

loc_2E1:
cpi	r16, 4
brne	loc_2E5
ldi	r17, 4
rjmp	loc_2F0

loc_2E5:
cpi	r16, 8
brne	loc_2E9
ldi	r17, 8
rjmp	loc_2F0

loc_2E9:
cpi	r16, 0x20 ; ' '
brne	loc_2ED
ldi	r17, 0x20 ; ' '
rjmp	loc_2F0

loc_2ED:
cpi	r16, 0x10
brne	loc_2F0
ldi	r17, 0x10

loc_2F0:
ldi	r30, 1
sts	unk_20017B, r30

loc_2F3:
mov	r30, r17

loc_2F4:
rcall	sub_88B
ret
; End of function sub_28A




sub_2F6:
rcall	sub_7B0
rcall	sub_3F8
rcall	sub_7B3
rcall	sub_7B6
ldi	r30, 0
sts	unk_20017C, r30
sts	unk_20017D, r30
rcall	sub_7B9
rcall	sub_7BD
rcall	sub_7C1
rcall	sub_7CC
ret
; End of function sub_2F6




sub_304:
rcall	sub_7B6
rcall	sub_7C1
ret
; End of function sub_304

; START	OF FUNCTION CHUNK FOR sub_74A

loc_307:
ldd	r30, Y+1
rcall	sub_7D0
rcall	sub_7D2
brne	loc_312
ldi	r30, 0x4B ; 'K'
ldi	r31, 0
sts	unk_200184, r30
sts	unk_200185, r31
rcall	sub_7D5

loc_312:
ldi	r30, 0
sts	unk_200180, r30
sts	unk_200181, r30
rjmp	loc_580
; END OF FUNCTION CHUNK	FOR sub_74A



sub_318:
ld	r30, Y
rcall	sub_7D0
ld	r30, Y
sts	unk_200183, r30
ldi	r30, 0x64 ; 'd'
ldi	r31, 0
sts	unk_200180, r30
sts	unk_200181, r31
rcall	sub_7D9
ldi	r30, 0
sts	unk_200184, r30
sts	unk_200185, r30
rcall	sub_7D5
rjmp	loc_444
; End of function sub_318




sub_32B:
rcall	sub_7B0
rcall	sub_410
rcall	sub_7B6
rcall	sub_7B3
ret
; End of function sub_32B




sub_330:
ldi	r30, 1
sts	unk_20017F, r30
ret
; End of function sub_330




sub_334:
rcall	sub_7BD
ret
; End of function sub_334

; START	OF FUNCTION CHUNK FOR sub_733

loc_336:
sbiw	r28, 2
rcall	sub_7DD
andi	r31, 0
std	Y+6, r30
std	Y+7, r31
ldi	r16, 0
ldi	r17, 0

loc_33D:
rcall	sub_7E0
brcc	loc_364
ldi	r18, 0
ldi	r19, 0

loc_341:
cpi	r18, 0x20 ; ' '
ldi	r30, 0x4E ; 'N'
cpc	r19, r30
brcc	loc_349
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_341

loc_349:
rcall	sub_76D
rcall	sub_3F8
ldi	r18, 0
ldi	r19, 0

loc_34D:
cpi	r18, 0x30 ; '0'
ldi	r30, 0x75 ; 'u'
cpc	r19, r30
brcc	loc_355
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_34D

loc_355:
rcall	sub_76D
rcall	sub_410
ldi	r18, 0
ldi	r19, 0

loc_359:
cpi	r18, 0x30 ; '0'
ldi	r30, 0x75 ; 'u'
cpc	r19, r30
brcc	loc_361
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_359

loc_361:
subi	r16, -1
sbci	r17, -1
rjmp	loc_33D

loc_364:
ldd	r30, Y+8
ldd	r31, Y+9
andi	r31, 0
std	Y+6, r30
std	Y+7, r31
ldi	r16, 0
ldi	r17, 0

loc_36B:
rcall	sub_7E0
brcc	loc_392
ldi	r18, 0
ldi	r19, 0

loc_36F:
cpi	r18, 0x20 ; ' '
ldi	r30, 0x4E ; 'N'
cpc	r19, r30
brcc	loc_377
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_36F

loc_377:
rcall	sub_777
rcall	sub_3F8
ldi	r18, 0
ldi	r19, 0

loc_37B:
cpi	r18, 0x30 ; '0'
ldi	r30, 0x75 ; 'u'
cpc	r19, r30
brcc	loc_383
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_37B

loc_383:
rcall	sub_777
rcall	sub_410
ldi	r18, 0
ldi	r19, 0

loc_387:
cpi	r18, 0x30 ; '0'
ldi	r30, 0x75 ; 'u'
cpc	r19, r30
brcc	loc_38F
rcall	sub_7E5
subi	r18, -1
sbci	r19, -1
rjmp	loc_387

loc_38F:
subi	r16, -1
sbci	r17, -1
rjmp	loc_36B

loc_392:
rjmp	loc_68B
; END OF FUNCTION CHUNK	FOR sub_733



sub_393:
rcall	sub_7EB
breq	loc_3B0
lds	r30, unk_200180
lds	r31, unk_200181
sbiw	r30, 1
sts	unk_200180, r30
sts	unk_200181, r31
rcall	sub_7EB
breq	loc_3AD
lds	r30, unk_200182
subi	r30, 1
sts	unk_200182, r30
cpi	r30, 0
brne	loc_3AC
lds	r30, unk_200183
st	-Y, r30
rcall	sub_428
rcall	sub_7D9

loc_3AC:
rjmp	loc_3AF

loc_3AD:
rcall	sub_7B6
rcall	sub_7CC

loc_3AF:
rjmp	loc_3BF

loc_3B0:
rcall	sub_7F1
breq	loc_3BF
lds	r30, unk_200184
lds	r31, unk_200185
sbiw	r30, 1
sts	unk_200184, r30
sts	unk_200185, r31
rcall	sub_7F1
brne	loc_3BF
rcall	sub_7B6
rcall	sub_7CC

loc_3BF:
lds	r30, unk_20017F
cpi	r30, 0
breq	loc_3C6
rcall	sub_7B0
rcall	sub_3F8
rjmp	loc_3D0

loc_3C6:
lds	r30, unk_20017E
subi	r30, 1
sts	unk_20017E, r30
cpi	r30, 0
brne	loc_3D0
rcall	sub_7B0
rcall	sub_428
rcall	sub_7B9

loc_3D0:
rcall	sub_27C
cpi	r30, 0
breq	loc_3F6
lds	r30, unk_20017C
lds	r31, unk_20017D
adiw	r30, 1
sts	unk_20017C, r30
sts	unk_20017D, r31
lds	r26, unk_20017C
lds	r27, unk_20017D
cpi	r26, -0x18 ; 'Ë'
ldi	r30, 3
cpc	r27, r30
brcs	loc_3E9
ldi	r30, 0
sts	unk_20017C, r30
sts	unk_20017D, r30

loc_3E9:
lds	r26, unk_20017C
lds	r27, unk_20017D
cpi	r26, 0xA
ldi	r30, 0
cpc	r27, r30
brcc	loc_3F4
ldi	r30, 0
rcall	sub_7D0
rjmp	loc_3F5

loc_3F4:
rcall	sub_7B3

loc_3F5:
rjmp	locret_3F7

loc_3F6:
rcall	sub_7B3

locret_3F7:
ret
; End of function sub_393




sub_3F8:
rcall	sub_7F7
brne	loc_3FC
cbi	PORTD, PORTD7
rjmp	loc_40F

loc_3FC:
rcall	sub_7FA
brne	loc_400
cbi	PORTD, PORTD6
rjmp	loc_40F

loc_400:
rcall	sub_7FD
brne	loc_404
cbi	PORTD, PORTD5
rjmp	loc_40F

loc_404:
rcall	sub_800
brne	loc_408
cbi	PORTD, PORTD4
rjmp	loc_40F

loc_408:
rcall	sub_803
breq	loc_40C
rcall	sub_7D2
brne	loc_40F

loc_40C:
in	r30, PORTD
andi	r30, -0x61
out	PORTD, r30

loc_40F:
rjmp	loc_444
; End of function sub_3F8




sub_410:
rcall	sub_7F7
brne	loc_414
sbi	PORTD, PORTD7
rjmp	loc_427

loc_414:
rcall	sub_7FA
brne	loc_418
sbi	PORTD, PORTD6
rjmp	loc_427

loc_418:
rcall	sub_7FD
brne	loc_41C
sbi	PORTD, PORTD5
rjmp	loc_427

loc_41C:
rcall	sub_800
brne	loc_420
sbi	PORTD, PORTD4
rjmp	loc_427

loc_420:
rcall	sub_803
breq	loc_424
rcall	sub_7D2
brne	loc_427

loc_424:
in	r30, PORTD
ori	r30, 0x60
out	PORTD, r30

loc_427:
rjmp	loc_444
; End of function sub_410




sub_428:
rcall	sub_7F7
brne	loc_42D
in	r30, PORTD
ldi	r26, -0x80 ; 'Ä'
rjmp	loc_442

loc_42D:
rcall	sub_7FA
brne	loc_432
in	r30, PORTD
ldi	r26, 0x40 ; '@'
rjmp	loc_442

loc_432:
rcall	sub_7FD
brne	loc_437
in	r30, PORTD
ldi	r26, 0x20 ; ' '
rjmp	loc_442

loc_437:
rcall	sub_800
brne	loc_43C
in	r30, PORTD
ldi	r26, 0x10
rjmp	loc_442

loc_43C:
rcall	sub_803
breq	loc_440
rcall	sub_7D2
brne	loc_444

loc_440:
in	r30, PORTD
ldi	r26, 0x60 ; '`'

loc_442:
eor	r30, r26
out	PORTD, r30

loc_444:
adiw	r28, 1
ret
; End of function sub_428




sub_446:
ldi	r30, 0x55 ; 'U'
sts	unk_200189, r30
sts	unk_20018A, r30
sts	unk_20018B, r30
ldi	r30, -0x7B ; 'Ö'
sts	unk_20018C, r30
sts	unk_20018D, r30
sts	unk_20018E, r30
ldi	r30, -0x7B ; 'Ö'
ldi	r31, -0x7F ; 'Å'
rcall	sub_736
ldi	r30, 0x1F
ldi	r31, -0x7E ; 'Ç'
rcall	sub_736
ldi	r30, -0x10 ; ''
ldi	r31, -0x7D ; 'É'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x7C ; 'Ñ'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x7B ; 'Ö'
rcall	sub_736
ldi	r30, -0x3F ; '¡'
ldi	r31, -0x72 ; 'é'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x71 ; 'è'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x70 ; 'ê'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x6F ; 'ë'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x6E ; 'í'
rcall	sub_736
ldi	r30, -0x78 ; 'à'
ldi	r31, -0x77 ; 'â'
rcall	sub_736
rcall	sub_58A
ret
; End of function sub_446

; START	OF FUNCTION CHUNK FOR sub_74D

loc_477:
ld	r30, Y
ldd	r31, Y+1
sts	unk_200187, r30
sts	unk_200188, r31
cpi	r30, 0x41 ; 'A'
ldi	r26, 0x21 ; '!'
cpc	r31, r26
brne	loc_48E
ldi	r30, 0xF
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x60 ; '†'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x5A ; '¶'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x28 ; '('
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_48E:
cpi	r30, 0x42 ; 'B'
ldi	r26, 0x21 ; '!'
cpc	r31, r26
brne	loc_49D
ldi	r30, -0x10 ; ''
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x60 ; '`'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x53 ; '≠'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
rcall	sub_806
rjmp	loc_580

loc_49D:
cpi	r30, 0x43 ; 'C'
ldi	r26, 0x21 ; '!'
cpc	r31, r26
brne	loc_4AC
ldi	r30, -8	; '¯'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x30 ; '0'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x47 ; 'π'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
rcall	sub_809
rjmp	loc_580

loc_4AC:
cpi	r30, 0x44 ; 'D'
ldi	r26, 0x21 ; '!'
cpc	r31, r26
brne	loc_4BD
ldi	r30, 0
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x3B ; '≈'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x68 ; 'h'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_4BD:
cpi	r30, 0x41 ; 'A'
ldi	r26, 0x22 ; '"'
cpc	r31, r26
brne	loc_4CE
ldi	r30, 7
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x30 ; '–'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x33 ; 'Õ'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x38 ; '8'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_4CE:
cpi	r30, 0x42 ; 'B'
ldi	r26, 0x22 ; '"'
cpc	r31, r26
brne	loc_4DF
ldi	r30, 0x1F
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x40 ; '@'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x28 ; 'ÿ'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x10 ; ''
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_4DF:
cpi	r30, 0x43 ; 'C'
ldi	r26, 0x22 ; '"'
cpc	r31, r26
brne	loc_4F0
ldi	r30, 0x27 ; '''
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x10
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x1C ; '‰'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x58 ; '®'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_4F0:
cpi	r30, 0x44 ; 'D'
ldi	r26, 0x22 ; '"'
cpc	r31, r26
brne	loc_501
ldi	r30, 0x2E ; '.'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x20 ; '‡'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -0x14 ; 'Ï'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x78 ; 'x'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_501:
cpi	r30, 0x41 ; 'A'
ldi	r26, 0x23 ; '#'
cpc	r31, r26
brne	loc_512
ldi	r30, 0x36 ; '6'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x50 ; '∞'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, -8	; '¯'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x30 ; '0'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_512:
cpi	r30, 0x42 ; 'B'
ldi	r26, 0x23 ; '#'
cpc	r31, r26
brne	loc_521
ldi	r30, 0x3E ; '>'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
rcall	sub_80C
ldi	r30, 3
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x18 ; 'Ë'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_521:
cpi	r30, 0x43 ; 'C'
ldi	r26, 0x23 ; '#'
cpc	r31, r26
brne	loc_530
ldi	r30, -0x3F ; '¡'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
rcall	sub_80C
ldi	r30, 0xB
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x48 ; '∏'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_530:
cpi	r30, 0x44 ; 'D'
ldi	r26, 0x23 ; '#'
cpc	r31, r26
brne	loc_541
ldi	r30, -0x37 ; '…'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x50 ; 'P'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, 0x17
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x70 ; 'p'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_541:
cpi	r30, 0x41 ; 'A'
ldi	r26, 0x24 ; '$'
cpc	r31, r26
brne	loc_552
ldi	r30, -0x4B ; 'µ'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x38 ; '»'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, 0x1F
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, 0x40 ; '@'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
rjmp	loc_580

loc_552:
cpi	r30, 0x42 ; 'B'
ldi	r26, 0x24 ; '$'
cpc	r31, r26
brne	loc_561
ldi	r30, -0x2F ; '—'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, 0x20 ; ' '
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, 0x2A ; '*'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
rcall	sub_806
rjmp	loc_580

loc_561:
cpi	r30, 0x43 ; 'C'
ldi	r26, 0x24 ; '$'
cpc	r31, r26
brne	loc_570
ldi	r30, -0x20 ; '‡'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x40 ; '¿'
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, 0x36 ; '6'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
rcall	sub_809
rjmp	loc_580

loc_570:
cpi	r30, 0x44 ; 'D'
ldi	r26, 0x24 ; '$'
cpc	r31, r26
brne	loc_580
ldi	r30, -0x28 ; 'ÿ'
ldi	r31, -0x79 ; 'á'
rcall	sub_736
ldi	r30, -0x10 ; ''
ldi	r31, -0x78 ; 'à'
rcall	sub_736
ldi	r30, 0x3E ; '>'
ldi	r31, -0x76 ; 'ä'
rcall	sub_736
ldi	r30, -0x80 ; 'Ä'
ldi	r31, -0x75 ; 'ã'
rcall	sub_736
; END OF FUNCTION CHUNK	FOR sub_74D
; START	OF FUNCTION CHUNK FOR sub_223

loc_580:
adiw	r28, 2
ret
; END OF FUNCTION CHUNK	FOR sub_223



sub_582:
sbi	PORTD, PORTD3
ldi	r30, -0x10 ; ''
ldi	r31, -0x7A ; 'Ü'
rcall	sub_736
cbi	PORTD, PORTD3
ret
; End of function sub_582




sub_588:
sbi	PORTD, PORTD3
ret
; End of function sub_588




sub_58A:
sbi	PORTD, PORTD3
ldi	r30, 0x30 ; '0'
ldi	r31, -0x7A ; 'Ü'
rcall	sub_736
cbi	PORTD, PORTD3
ret
; End of function sub_58A

; START	OF FUNCTION CHUNK FOR sub_736

loc_590:
st	-Y, r16
ldd	r30, Y+1
ldd	r31, Y+2
andi	r30, 0
mov	r30, r31
ldi	r31, 0
mov	r16, r30
cbi	PORTB, PORTB2
rcall	sub_80F
ldd	r16, Y+1
rcall	sub_80F
ser	r30
st	-Y, r30
rcall	sub_223
sbi	PORTB, PORTB2
ld	r16, Y
adiw	r28, 3
ret
; END OF FUNCTION CHUNK	FOR sub_736



sub_5A2:
sbiw	r28, 3
rcall	sub_7DD
rcall	sub_811
ldi	r30, -0x71 ; 'è'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x71 ; 'è'
ldi	r31, 1
push	r31
push	r30
rcall	sub_824
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x70 ; 'ê'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x70 ; 'ê'
ldi	r31, 1
push	r31
push	r30
rcall	sub_828
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x6F ; 'ë'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x6F ; 'ë'
ldi	r31, 1
push	r31
push	r30
rcall	sub_82C
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x6E ; 'í'
ldi	r31, 1
rcall	sub_830
ldi	r30, -0x6E ; 'í'
ldi	r31, 1
push	r31
push	r30
rcall	sub_835
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x71 ; 'è'
ldi	r31, 1
ld	r19, Z
ldi	r18, 7

loc_5D5:
ldi	r30, 9
cp	r30, r18
brcs	loc_5DF
rcall	sub_83B
subi	r30, 0x77 ; 'w'
sbci	r31, -2	; '˛'
ld	r30, Z
add	r19, r30
subi	r18, -1
rjmp	loc_5D5

loc_5DF:
sts	unk_200193, r19
lds	r30, unk_20018F
rcall	sub_83E
ori	r21, -0x6D
rcall	sub_842
lds	r30, unk_200190
rcall	sub_83E
ori	r21, -0x6C
rcall	sub_842
lds	r30, unk_200191
rcall	sub_83E
ori	r21, -0x6B
rcall	sub_842
lds	r30, unk_200192
rcall	sub_83E
ori	r21, -0x6A
rcall	sub_842
rcall	sub_845
breq	loc_5FA
rcall	sub_848
rcall	sub_84B
rcall	sub_84E

loc_5FA:
rcall	sub_582
ldi	r16, -0x77 ; 'â'
ldi	r17, 1
st	-Y, r17
st	-Y, r16
rcall	possible_UART_sub_6D9
rcall	sub_588
rjmp	loc_68B
; End of function sub_5A2




sub_602:
sbiw	r28, 3
rcall	sub_87D
ldi	r30, 0x55 ; 'U'
sts	unk_200194, r30
sts	unk_200195, r30
sts	unk_200196, r30
sts	unk_200197, r30
sts	unk_200198, r30
sts	unk_200199, r30
lds	r30, unk_20018C
sts	unk_20019A, r30
lds	r30, unk_20018D
sts	unk_20019B, r30
lds	r30, unk_20018E
sts	unk_20019C, r30
lds	r30, unk_20018F
sts	unk_20019D, r30
lds	r30, unk_200190
sts	unk_20019E, r30
lds	r30, unk_200191
sts	unk_20019F, r30
lds	r30, unk_200192
sts	unk_2001A0, r30
ldd	r30, Y+9
rcall	sub_811
ldi	r30, -0x63 ; 'ù'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x63 ; 'ù'
ldi	r31, 1
push	r31
push	r30
rcall	sub_824
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x62 ; 'û'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x62 ; 'û'
ldi	r31, 1
push	r31
push	r30
rcall	sub_828
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x61 ; 'ü'
ldi	r31, 1
rcall	sub_81F
ldi	r30, -0x61 ; 'ü'
ldi	r31, 1
push	r31
push	r30
rcall	sub_82C
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x60 ; '†'
ldi	r31, 1
rcall	sub_830
ldi	r30, -0x60 ; '†'
ldi	r31, 1
push	r31
push	r30
rcall	sub_835
pop	r26
pop	r27
st	X, r30
ldi	r30, -0x63 ; 'ù'
ldi	r31, 1
ld	r19, Z
ldi	r18, 0xA

loc_65F:
ldi	r30, 0xC
cp	r30, r18
brcs	loc_669
rcall	sub_83B
subi	r30, 0x6C ; 'l'
sbci	r31, -2	; '˛'
ld	r30, Z
add	r19, r30
subi	r18, -1
rjmp	loc_65F

loc_669:
sts	unk_2001A1, r19
lds	r30, unk_20019D
rcall	sub_83E
ori	r21, -0x6D
rcall	sub_842
lds	r30, unk_20019E
rcall	sub_83E
ori	r21, -0x6C
rcall	sub_842
lds	r30, unk_20019F
rcall	sub_83E
ori	r21, -0x6B
rcall	sub_842
lds	r30, unk_2001A0
rcall	sub_83E
ori	r21, -0x6A
rcall	sub_842
rcall	sub_845
breq	loc_684
rcall	sub_848
rcall	sub_84B
rcall	sub_84E

loc_684:
rcall	sub_582
ldi	r16, -0x6C ; 'î'
ldi	r17, 1
st	-Y, r17
st	-Y, r16
rcall	sub_6CF
rcall	sub_588

loc_68B:
rcall	sub_884
adiw	r28, 0xA
ret
; End of function sub_602




sub_68E:
rcall	sub_87F
rcall	sub_20A
mov	r16, r30
rcall	sub_20E
mov	r17, r30
rcall	sub_212
mov	r18, r30
rcall	sub_851
andi	r30, 4
mov	r19, r30
mov	r30, r16
rcall	left_shift_sub_875
andi	r30, -8
or	r19, r30
mov	r30, r17
swap	r30
andi	r30, 0xF
lsr	r30
lsr	r30
lsr	r30
andi	r30, 1
or	r19, r30
sts	unk_20018F, r19
mov	r30, r16
swap	r30
andi	r30, 0xF
lsr	r30
lsr	r30
rcall	sub_856
lsl	r30
andi	r30, -4
or	r19, r30
sts	unk_200190, r19
rcall	sub_851
rcall	sub_856
swap	r30
andi	r30, -0x10
lsl	r30
lsl	r30
lsl	r30
andi	r30, -0x80
or	r19, r30
mov	r30, r18
lsr	r30
andi	r30, 0x7C
or	r19, r30
sts	unk_200191, r19
mov	r30, r18
swap	r30
andi	r30, -0x10
lsl	r30
andi	r30, -0x20
mov	r19, r30
mov	r30, r18
swap	r30
andi	r30, 0x10
or	r19, r30
sts	unk_200192, r19
rcall	sub_886
adiw	r28, 4
ret
; End of function sub_68E




sub_6CF:
rcall	WTF_sub_85A
sbi	DDRD, DDD1
cli							;WHAT THE FUCK AM I DOING WITH MY LIFE???
ld	r26, Y
ldd	r27, Y+1
ldi	r22, 8
ldi	r23, 0xE
rjmp	loc_6E0
; End of function sub_6CF

.dw 0x9622 ; "ñ
.dw 0x9508 ;  ï



possible_UART_sub_6D9:
rcall	WTF_sub_85A
sbi	DDRD, DDD1
cli
ld	r26, Y
ldd	r27, Y+1
ldi	r22, 8
ldi	r23, 0xB

loc_6E0:
ld	r24, X
adiw	r26, 1

loc_6E2:
sbrs	r24, 7		
rjmp	loc_6E9		;conditional jump
nop					;nopsled= delay for serial communication???
nop
nop
sbi	PORTD, PORTD1	;PORTD1=1
rjmp	loc_6EE

loc_6E9:
nop
nop
cbi	PORTD, PORTD1	;PORTD1=0
nop
nop

loc_6EE:
subi	r22, 1
breq	loc_6FE
lsl	r24
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
rjmp	loc_6E2

loc_6FE:
subi	r23, 1		;counter, counts 8 bits for serial communicaion
breq	loc_707
ldi	r22, 8
nop
nop
nop
nop
nop
rjmp	loc_6E0

loc_707:
sei
ldi	r25, 5			;-

loc_709:			;-
subi	r25, 1		;-
brne	loc_709		;5-cycle delay
cbi	DDRD, DDD1		;done writing to PORTD1
adiw	r28, 2
ret
; End of function possible_UART_sub_6D9




sub_70E:
ldi	r30, 4
ldi	r31, 0
sts	unk_20016E, r30
sts	unk_20016F, r31
ret
; End of function sub_70E




sub_715:
ldi	r30, 5
ldi	r31, 0
sts	unk_200170, r30
sts	unk_200171, r31
ret
; End of function sub_715




sub_71C:
lds	r30, unk_20016C
lds	r31, unk_20016D
sbiw	r30, 0
ret
; End of function sub_71C




sub_722:
lds	r30, unk_200169
cpi	r30, 0
ret
; End of function sub_722




sub_726:
ldi	r30, 0
sts	unk_200167, r30
ret
; End of function sub_726



; Attributes: noreturn

sub_72A:
ldi	r30, 0
ldi	r31, 0
st	-Y, r31
st	-Y, r30
rjmp	sub_1F0
; End of function sub_72A




sub_72F:
lds	r26, unk_200162
cpi	r26, -1
ret
; End of function sub_72F




sub_733:

; FUNCTION CHUNK AT 0336 SIZE 0000005D BYTES

st	-Y, r31
st	-Y, r30
rjmp	loc_336
; End of function sub_733




sub_736:

; FUNCTION CHUNK AT 0590 SIZE 00000012 BYTES

st	-Y, r31
st	-Y, r30
rjmp	loc_590
; End of function sub_736




sub_739:
ldi	r30, 0x18
ldi	r31, 0x15
sts	unk_20016A, r30
sts	unk_20016B, r31
ret
; End of function sub_739




sub_740:
lds	r30, unk_200162
cpi	r30, 2
ret
; End of function sub_740




sub_744:
mov	r30, r16
ldi	r31, 0
ret
; End of function sub_744




sub_747:
ldi	r30, 4
st	-Y, r30
ret
; End of function sub_747




sub_74A:

; FUNCTION CHUNK AT 0307 SIZE 00000011 BYTES

ldi	r30, 0
st	-Y, r30
rjmp	loc_307
; End of function sub_74A




sub_74D:

; FUNCTION CHUNK AT 0477 SIZE 00000109 BYTES

sts	unk_200160, r30
sts	unk_200161, r31
st	-Y, r31
st	-Y, r30
rjmp	loc_477
; End of function sub_74D




sub_754:
ldi	r30, 3
sts	unk_200163, r30
ret
; End of function sub_754




sub_758:
ldi	r30, 1
sts	unk_200166, r30
ret
; End of function sub_758




sub_75C:
rcall	sub_304
lds	r30, unk_200165
lds	r26, unk_200164
or	r30, r26
st	-Y, r30
ret
; End of function sub_75C




sub_764:
clr	r5
ldi	r30, 1
ldi	r31, 0
sts	unk_20016C, r30
sts	unk_20016D, r31
ldi	r30, 5
ret
; End of function sub_764




sub_76D:
ldi	r30, 3
st	-Y, r30
ret
; End of function sub_76D




sub_770:
ldi	r30, 7
sts	unk_200163, r30
ret
; End of function sub_770




sub_774:
ldi	r30, 1
cp	r30, r5
ret
; End of function sub_774




sub_777:
ldi	r30, 2
st	-Y, r30
ret
; End of function sub_777




sub_77A:
ldi	r30, 1
st	-Y, r30
rjmp	loc_307
; End of function sub_77A




sub_77D:
ldi	r30, 4
sts	unk_200163, r30
ret
; End of function sub_77D




sub_781:
ldi	r30, 0x64 ; 'd'
sts	unk_200169, r30
ret
; End of function sub_781




sub_785:
ldi	r30, 0x63 ; 'c'
out	TCNT0, r30
ret
; End of function sub_785




sub_788:
ldi	r30, 0
sts	unk_20017B, r30
ret
; End of function sub_788




sub_78C:
ldi	r30, 0
sts	unk_200178, r30
ret
; End of function sub_78C




sub_790:
ldi	r30, 1
sts	unk_200179, r30
ldi	r30, 0
sts	unk_20017A, r30
ret
; End of function sub_790




sub_797:
lds	r30, unk_20017A
subi	r30, -1
sts	unk_20017A, r30
lds	r26, unk_20017A
ldi	r30, -0x38 ; '»'
cp	r30, r26
ret
; End of function sub_797




sub_7A1:
ldi	r30, 0
sts	unk_20017A, r30
sts	unk_200179, r30
ldi	r30, 0x11
ret
; End of function sub_7A1




sub_7A8:
lds	r30, unk_200179
cpi	r30, 0
ret
; End of function sub_7A8




sub_7AC:
lds	r26, unk_200177
cp	r16, r26
ret
; End of function sub_7AC




sub_7B0:
ldi	r30, 5
st	-Y, r30
ret
; End of function sub_7B0




sub_7B3:
ldi	r30, 0
st	-Y, r30
rjmp	sub_410
; End of function sub_7B3




sub_7B6:
ldi	r30, 1
st	-Y, r30
rjmp	sub_410
; End of function sub_7B6




sub_7B9:
ldi	r30, 0x32 ; '2'
sts	unk_20017E, r30
ret
; End of function sub_7B9




sub_7BD:
ldi	r30, 0
sts	unk_20017F, r30
ret
; End of function sub_7BD




sub_7C1:
ldi	r30, 0
sts	unk_200180, r30
sts	unk_200181, r30
ldi	r30, 0
sts	unk_200184, r30
sts	unk_200185, r30
ret
; End of function sub_7C1




sub_7CC:
ldi	r30, 0
sts	unk_200186, r30
ret
; End of function sub_7CC




sub_7D0:
st	-Y, r30
rjmp	sub_3F8
; End of function sub_7D0




sub_7D2:
ld	r26, Y
cpi	r26, 1
ret
; End of function sub_7D2




sub_7D5:
ldi	r30, 1
sts	unk_200186, r30
ret
; End of function sub_7D5




sub_7D9:
ldi	r30, 0xA
sts	unk_200182, r30
ret
; End of function sub_7D9




sub_7DD:
rcall	sub_87D
ldd	r30, Y+9
ret
; End of function sub_7DD




sub_7E0:
ldd	r30, Y+6
ldd	r31, Y+7
cp	r16, r30
cpc	r17, r31
ret
; End of function sub_7E0




sub_7E5:
mov	r30, r18
mov	r31, r19
adiw	r30, 1
mov	r20, r30
mov	r21, r31
ret
; End of function sub_7E5




sub_7EB:
lds	r30, unk_200180
lds	r31, unk_200181
sbiw	r30, 0
ret
; End of function sub_7EB




sub_7F1:
lds	r30, unk_200184
lds	r31, unk_200185
sbiw	r30, 0
ret
; End of function sub_7F1




sub_7F7:
ld	r26, Y
cpi	r26, 5
ret
; End of function sub_7F7




sub_7FA:
ld	r26, Y
cpi	r26, 3
ret
; End of function sub_7FA




sub_7FD:
ld	r26, Y
cpi	r26, 2
ret
; End of function sub_7FD




sub_800:
ld	r30, Y
cpi	r30, 0
ret
; End of function sub_800




sub_803:
ld	r26, Y
cpi	r26, 4
ret
; End of function sub_803




sub_806:
ldi	r30, -8	; '¯'
ldi	r31, -0x75 ; 'ã'
rjmp	sub_736
; End of function sub_806




sub_809:
ldi	r30, -0x50 ; '∞'
ldi	r31, -0x75 ; 'ã'
rjmp	sub_736
; End of function sub_809




sub_80C:
ldi	r30, -0x80 ; 'Ä'
ldi	r31, -0x78 ; 'à'
rjmp	sub_736
; End of function sub_80C




sub_80F:
st	-Y, r16
rjmp	sub_223
; End of function sub_80F




sub_811:
swap	r30
andi	r30, 0xF
lsr	r30
andi	r30, 2
std	Y+8, r30
ldd	r30, Y+9
swap	r30
andi	r30, 2
std	Y+7, r30
ldd	r30, Y+9
rcall	right_shift_sub_879
andi	r30, 2
std	Y+6, r30
ret
; End of function sub_811




sub_81F:
movw	r26, r30
ld	r30, X
andi	r30, -3
st	X, r30
ret
; End of function sub_81F




sub_824:
ld	r30, Z
ldd	r26, Y+8
or	r30, r26
ret
; End of function sub_824




sub_828:
ld	r30, Z
ldd	r26, Y+7
or	r30, r26
ret
; End of function sub_828




sub_82C:
ld	r30, Z
ldd	r26, Y+6
or	r30, r26
ret
; End of function sub_82C




sub_830:
movw	r26, r30
ld	r30, X
andi	r30, -0x10
st	X, r30
ret
; End of function sub_830




sub_835:
ld	r30, Z
mov	r26, r30
ldd	r30, Y+9
andi	r30, 0xF
or	r30, r26
ret
; End of function sub_835




sub_83B:
mov	r30, r18
ldi	r31, 0
ret
; End of function sub_83B




sub_83E:
ldi	r31, 0
mov	r20, r30
mov	r21, r31
ret
; End of function sub_83E




sub_842:
st	-Y, r21
st	-Y, r20
rjmp	loc_590
; End of function sub_842




sub_845:
rcall	sub_43
cpi	r30, 0
ret
; End of function sub_845




sub_848:
ldi	r30, 0x55 ; 'U'
ldi	r31, -0x6D ; 'ì'
rjmp	sub_736
; End of function sub_848




sub_84B:
ldi	r30, 0x55 ; 'U'
ldi	r31, -0x6C ; 'î'
rjmp	sub_736
; End of function sub_84B




sub_84E:
ldi	r30, 0x55 ; 'U'
ldi	r31, -0x6B ; 'ï'
rjmp	sub_736
; End of function sub_84E




sub_851:
mov	r30, r16
swap	r30
andi	r30, 0xF
lsr	r30
ret
; End of function sub_851




sub_856:
andi	r30, 1
mov	r19, r30
mov	r30, r17
ret
; End of function sub_856




WTF_sub_85A:
ld	r30, Y
ldd	r31, Y+1
st	Y, r30
std	Y+1, r31
ret
; End of function WTF_sub_85A




sub_85F:
cp	r26, r30
cpc	r27, r31
ldi	r30, 1
brcs	locret_864
clr	r30

locret_864:
ret
; End of function sub_85F




sub_865:
adiw	r26, 1			;r26+1
rcall	eeprom_read_sub_869			;call eeprom read
mov	r31, r30			;copy r30 to r31
sbiw	r26, 1			;r26-1
; End of function sub_865




eeprom_read_sub_869:
sbic	EECR, EEWE
rjmp	eeprom_read_sub_869
push	r31
in	r31, SREG
cli
out	EEARL, r26
out	EEARH, r27
sbi	EECR, EERE
in	r30, EEDR
out	SREG, r31
pop	r31
ret
; End of function eeprom_read_sub_869




left_shift_sub_875:
lsl	r30
lsl	r30
lsl	r30
ret
; End of function left_shift_sub_875




right_shift_sub_879:
lsr	r30
lsr	r30
lsr	r30
ret
; End of function right_shift_sub_879




sub_87D:
st	-Y, r21
st	-Y, r20
; End of function sub_87D




sub_87F:
st	-Y, r19
st	-Y, r18
; End of function sub_87F




sub_881:
st	-Y, r17
st	-Y, r16
ret
; End of function sub_881




sub_884:
ldd	r21, Y+5
ldd	r20, Y+4
; End of function sub_884




sub_886:
ldd	r19, Y+3
ldd	r18, Y+2
ldd	r17, Y+1
ld	r16, Y
ret
; End of function sub_886




sub_88B:
ld	r16, Y+
ld	r17, Y+
ret
; End of function sub_88B

.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF
.dw 0xFFFF


; Segment type:	Pure data
.DSEG ;	RAM
r0:.byte 1
r1:.byte 1
r2:.byte 1
r3:.byte 1
r4:.byte 1
r5:.byte 1
r6:.byte 1
r7:.byte 1
r8:.byte 1
r9:.byte 1
r10:.byte 1
r11:.byte 1
r12:.byte 1
r13:.byte 1
r14:.byte 1
r15:.byte 1
r16:.byte 1
r17:.byte 1
r18:.byte 1
r19:.byte 1
r20:.byte 1
r21:.byte 1
r22:.byte 1
r23:.byte 1
r24:.byte 1
r25:.byte 1
r26:.byte 1
r27:.byte 1
r28:.byte 1
r29:.byte 1
r30:.byte 1
r31:.byte 1
TWBR:.byte 1		; Two-wire Serial Interface Bit	Rate Register
TWSR:.byte 1		; TWI Status Register
TWAR:.byte 1		; TWI (Slave) Address Register
TWDR:.byte 1		; TWI Data Register
ADCL:.byte 1		; ADC Data Register Low	(ADLAR = 0)
ADCH:.byte 1		; ADC Data Register High (ADLAR	= 0)
ADCSRA:.byte 1		; ADC Control and Status Register A
ADMUX:.byte 1		; ADC Multiplexer Selection Register
ACSR:.byte 1		; Analog Comparator Control and	Status Register
UBRRL:.byte 1		; USART	Baud Rate Register Low
UCSRB:.byte 1		; USART	Control	and Status Register B
UCSRA:.byte 1		; USART	Control	and Status Register A
UDR:.byte 1		; USART	I/O Data Register
SPCR:.byte 1		; SPI Control Register
SPSR:.byte 1		; SPI Status Register
SPDR:.byte 1		; SPI Data Register
PIND:.byte 1		; Port D Input Pins Address
DDRD:.byte 1		; Port D Data Direction	Register
PORTD:.byte 1		; Port D Data Register
PINC:.byte 1		; Port C Input Pins Address
DDRC:.byte 1		; Port C Data Direction	Register
PORTC:.byte 1		; Port C Data Register
PINB:.byte 1		; Port B Input Pins Address
DDRB:.byte 1		; Port B Data Direction	Register
PORTB:.byte 1		; Port B Data Register
RESERVED0019:.byte 1	; RESERVED
RESERVED001A:.byte 1	; RESERVED
RESERVED001B:.byte 1	; RESERVED
EECR:.byte 1		; EEPROM Control Register
EEDR:.byte 1		; EEPROM Data Register
EEARL:.byte 1		; EEPROM Address Register Low
EEARH:.byte 1		; EEPROM Address Register High
UCSRC:.byte 1		; USART	Control	and Status Register (page 148)
WDTCR:.byte 1		; Watchdog Timer Control Register
ASSR:.byte 1		; Asynchronous Status Register
OCR2:.byte 1		; Output Compare Register
TCNT2:.byte 1		; Timer/Counter	Register
TCCR2:.byte 1		; Timer/Counter	Control	Register
ICR1L:.byte 1		; Input	Capture	Register 1 Low
ICR1H:.byte 1		; Input	Capture	Register 1 High
OCR1BL:.byte 1		; Output Compare Register 1 B Low
OCR1BH:.byte 1		; Output Compare Register 1 B High
OCR1AL:.byte 1		; Output Compare Register 1 A Low
OCR1AH:.byte 1		; Output Compare Register 1 A High
TCNT1L:.byte 1		; Timer/Counter	1 Low
TCNT1H:.byte 1		; Timer/Counter	1 High
TCCR1B:.byte 1		; Timer/Counter	1 Control Register B
TCCR1A:.byte 1		; Timer/Counter	1 Control Register A
SFIOR:.byte 1		; Special Function IO Register
OSCCAL:.byte 1		; Oscillator Calibration Register
TCNT0:.byte 1		; Timer/Counter	Register
TCCR0:.byte 1		; Timer/Counter	Control	Register
MCUCSR:.byte 1		; MCU Control and Status Register
MCUCR:.byte 1		; MCU Control Register
TWCR:.byte 1		; TWI Control Register
SPMCR:.byte 1		; Store	Program	Memory Control Register
TIFR:.byte 1		; Timer/Counter	Interrupt Flag Register
TIMSK:.byte 1		; Timer/Counter	Interrupt Mask Register
GIFR:.byte 1		; General Interrupt Flag Register
GICR:.byte 1		; General Interrupt Control Register
RESERVED003C:.byte 1	; RESERVED
SPL:.byte 1		; Stack	Pointer	Low
SPH:.byte 1		; Stack	Pointer	High
SREG:.byte 1		; Status Register
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1
.byte 1


; Segment type:	Pure data
.DSEG ;	EEPROM
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x37 ; 7
.db 0x43 ; C
.db 0x44 ; D
.db 0x36 ; 6
.db 0x42 ; B
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x42 ; B
.db 0x31 ; 1
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x34 ; 4
.db 0x33 ; 3
.db 0x36 ; 6
.db 0x46 ; F
.db 0x37 ; 7
.db 0x30 ; 0
.db 0x37 ; 7
.db 0x39 ; 9
.db 0x37 ; 7
.db 0x32 ; 2
.db 0x36 ; 6
.db 0x39 ; 9
.db 0x36 ; 6
.db 0x37 ; 7
.db 0x36 ; 6
.db 0x38 ; 8
.db 0x37 ; 7
.db 0x34 ; 4
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x41 ; A
.db 0x39 ; 9
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x34 ; 4
.db 0x39 ; 9
.db 0x36 ; 6
.db 0x45 ; E
.db 0x37 ; 7
.db 0x34 ; 4
.db 0x36 ; 6
.db 0x35 ; 5
.db 0x41 ; A
.db 0x45 ; E
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x37 ; 7
.db 0x32 ; 2
.db 0x36 ; 6
.db 0x31 ; 1
.db 0x36 ; 6
.db 0x33 ; 3
.db 0x37 ; 7
.db 0x34 ; 4
.db 0x36 ; 6
.db 0x39 ; 9
.db 0x37 ; 7
.db 0x36 ; 6
.db 0x36 ; 6
.db 0x35 ; 5
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x34 ; 4
.db 0x43 ; C
.db 0x36 ; 6
.db 0x35 ; 5
.db 0x36 ; 6
.db 0x31 ; 1
.db 0x37 ; 7
.db 0x32 ; 2
.db 0x36 ; 6
.db 0x45 ; E
.db 0x36 ; 6
.db 0x39 ; 9
.db 0x36 ; 6
.db 0x45 ; E
.db 0x36 ; 6
.db 0x37 ; 7
.db 0x39 ; 9
.db 0x32 ; 2
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x35 ; 5
.db 0x36 ; 6
.db 0x36 ; 6
.db 0x35 ; 5
.db 0x37 ; 7
.db 0x32 ; 2
.db 0x37 ; 7
.db 0x33 ; 3
.db 0x36 ; 6
.db 0x39 ; 9
.db 0x36 ; 6
.db 0x46 ; F
.db 0x36 ; 6
.db 0x45 ; E
.db 0x32 ; 2
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x33 ; 3
.db 0x32 ; 2
.db 0x45 ; E
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x41 ; A
.db 0x36 ; 6
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x34 ; 4
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x33 ; 3
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x42 ; B
.db 0x37 ; 7
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x35 ; 5
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x42 ; B
.db 0x30 ; 0
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x36 ; 6
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x41 ; A
.db 0x30 ; 0
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x37 ; 7
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
unk_200160:.db 0x46 ; F
unk_200161:.db 0x46 ; F
unk_200162:.db 0x46 ; F
unk_200163:.db 0x46 ; F
unk_200164:.db 0x39 ; 9
unk_200165:.db 0x30 ; 0
unk_200166:.db	0xD
unk_200167:.db	0xA
unk_200168:.db 0x3A ; :
unk_200169:.db 0x31 ; 1
unk_20016A:.db 0x30 ; 0
unk_20016B:.db 0x30 ; 0
unk_20016C:.db 0x30 ; 0
unk_20016D:.db 0x38 ; 8
unk_20016E:.db 0x30 ; 0
unk_20016F:.db 0x30 ; 0
unk_200170:.db 0x30 ; 0
unk_200171:.db 0x46 ; F
unk_200172:.db 0x46 ; F
unk_200173:.db 0x46 ; F
unk_200174:.db 0x46 ; F
unk_200175:.db 0x46 ; F
unk_200176:.db 0x46 ; F
unk_200177:.db 0x46 ; F
unk_200178:.db 0x46 ; F
unk_200179:.db 0x46 ; F
unk_20017A:.db 0x46 ; F
unk_20017B:.db 0x46 ; F
unk_20017C:.db 0x46 ; F
unk_20017D:.db 0x46 ; F
unk_20017E:.db 0x46 ; F
unk_20017F:.db 0x46 ; F
unk_200180:.db 0x46 ; F
unk_200181:.db 0x46 ; F
unk_200182:.db 0x46 ; F
unk_200183:.db 0x46 ; F
unk_200184:.db 0x46 ; F
unk_200185:.db 0x46 ; F
unk_200186:.db 0x46 ; F
unk_200187:.db 0x46 ; F
unk_200188:.db 0x46 ; F
unk_200189:.db 0x46 ; F
unk_20018A:.db 0x46 ; F
unk_20018B:.db 0x46 ; F
unk_20018C:.db 0x46 ; F
unk_20018D:.db 0x46 ; F
unk_20018E:.db 0x46 ; F
unk_20018F:.db 0x46 ; F
unk_200190:.db 0x46 ; F
unk_200191:.db 0x38 ; 8
unk_200192:.db 0x30 ; 0
unk_200193:.db	0xD
unk_200194:.db	0xA
unk_200195:.db 0x3A ; :
unk_200196:.db 0x31 ; 1
unk_200197:.db 0x30 ; 0
unk_200198:.db 0x30 ; 0
unk_200199:.db 0x30 ; 0
unk_20019A:.db 0x39 ; 9
unk_20019B:.db 0x30 ; 0
unk_20019C:.db 0x30 ; 0
unk_20019D:.db 0x30 ; 0
unk_20019E:.db 0x46 ; F
unk_20019F:.db 0x46 ; F
unk_2001A0:.db 0x46 ; F
unk_2001A1:.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x37 ; 7
.db 0x30 ; 0
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x41 ; A
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x36 ; 6
.db 0x30 ; 0
.db  0xD
.db  0xA
.db 0x3A ; :
.db 0x31 ; 1
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x42 ; B
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x30 ; 0
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F
.db 0x46 ; F

.exit ;
